baseURL: "https://seth-woo.github.io/"
title: Seth Woo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        # - name: Blog
        #   url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        #   weight: 6

params:
    description: "This website hosts Seth Woo's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Seth Woo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Seth Woo
          subtitle: "Welcome to my websiteðŸ‘‹! I'm **Seth** or **Wai Hong** (**èƒ¡ä¼Ÿåº·**). <br><br> I am a research-driven builder and aspiring AI/ML researcher, with a background in DS/Analytics. I enjoy turning experiments into meaningful applications (and sometimes for funsiesðŸ˜œ) and currently seeking employment/mentorship/PhD opportunities in AI. <br><br> My research interests span **Generative Models**, **Large Language Models** (**LLMs**), **Post-Training of LLMs**, **Design and Optimization of Multimodal & Multi-model DL Pipelines**, **Computer Vision**, **Edge AI**, **Digital Twins** and **Virtualization**, **Trustworthy AI**, **Human-AI Interaction** & **Applications** across **Healthcare**, **Mobility**, **Sustainability**, and **Creative Industries**, as well as **World Models** and **Artificial General Intelligence** (**AGI**) <br><br> If any of the above interests you, or you are pursuing similar goals, Iâ€™d love to chat. Let's connect !"
          imageUrl: "Casual Seth.jpg"
          imageWidth: 180
          imageHeight: 180
          # buttons:
          #   - name: Papers
          #     url: papers/
          #   - name: Data
          #     url: data/
          #   - name: Books
          #     url: books/
          #   - name: Courses
          #     url: courses/
          #   - name: Tags
          #     url: tags/
          #   - name: Archive
          #     url: archive/
            # - name: Blog
            #   url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:sethwoo555@gmail.com
        - name: ORCID
          url: https://orcid.org/0000-0002-0324-4815
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/seth-woo
        - name: linkedin
          url: https://www.linkedin.com/in/sethwoo/
        - name: x
          url: https://x.com/woogamanga
        - name: Mastodon
          url: https://mastodon.social/@seth_woo
        - name: Bluesky
          url: https://bsky.app/profile/sethwoo.bsky.social
        - name: instagram
          url: https://www.instagram.com/21.09_wh/
        - name: discord 
          url: https://discord.com/users/484731835990147088
        - name: whatsapp
          url: https://wa.me/60126942981
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: tiktok
        #   url: https://www.tiktok.com/@pmichaillat
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Seth Woo"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2