baseURL: "https://seth-woo.github.io/"
title: Seth Woo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Publications
          # url: papers/
          url: https://seth-woo.github.io/
          weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        - name: Garden/Vault (:re)
          url: https://seth-woo.github.io/
          weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        #   weight: 6

params:
    description: "This website hosts Seth Woo's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Seth Woo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Seth Woo
          subtitle: |
            I'm **Seth** or **Wai Hong** (èƒ¡ä¼Ÿåº·).

            I am an aspiring AI/ML researcher, with a background in CompSci & DataSci. I thrive in R&D environments where I enjoy turning experiments into meaningful applications. At the moment, I am actively seeking PhD opportunities in **Continual Learning** (CL). I am primarily interested in exploring CL under **distributed**, **low-resource settings** for **non-stationary**, **non-i.i.d data streams** but am also open to adjacent topics such as **Online Learning**, **Active Learning**, **Meta-Learning**, **Open-World Learning**, **Few-Shot Learning**, **Transfer Learning**, **Domain Adaptation** and **Federated Learning** within the context of **Lifelong Learning**.

            If any of the above interests you, or you're pursuing similar goals, I'd love to chat. HMU! ðŸ‘¾
          imageUrl: "Minimal Seth.png"
          imageWidth: 165
          imageHeight: 165
          buttons:
            - name: Publications
              # url: papers/
              url: https://seth-woo.github.io/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            # - name: Archive
            #   url: archive/
            - name: Garden/Vault (:re)
              url: https://seth-woo.github.io/

    socialIcons:
        - name: CV
          url: "Curriculum Vitae - Waihong Woo (Seth).pdf"
        - name: Email
          url: mailto:sethwoo555@gmail.com
        - name: ORCID
          url: https://orcid.org/0000-0002-0324-4815
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/seth-woo
        - name: linkedin
          url: https://www.linkedin.com/in/sethwoo/
        - name: x
          url: https://x.com/woogamanga
        - name: Mastodon
          url: https://mastodon.social/@seth_woo
        - name: Bluesky
          url: https://bsky.app/profile/sethwoo.bsky.social
        - name: instagram
          url: https://www.instagram.com/21.09_wh/
        - name: discord 
          url: https://discord.com/users/484731835990147088
        - name: whatsapp
          url: https://wa.me/60126942981
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: tiktok
        #   url: https://www.tiktok.com/@pmichaillat
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Seth Woo"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
