baseURL: "https://seth-woo.github.io/"
title: Seth Woo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        #   weight: 6

params:
    description: "This website hosts Seth Woo's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Seth Woo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Seth Woo
          subtitle: "I'm **Seth** or **Wai Hong** (**胡伟康**). <br><br> I am a builder and aspiring AI/ML researcher, with a background in CS and DS/Analytics. I thrive in R&D and Agile environments where I enjoy turning experiments into meaningful applications. At the moment, I am actively seeking employment/mentorship/PhD opportunities in AI/ML. <br><br> My research interests span **Bioinformatics**, **Optimization**, **Geometric Deep Learning**, **Representation Learning** and **Optimal Transport** for mission-critical healthcare applications. <br><br> If any of the above interests you, or you are pursuing similar goals, I’d love to chat. Let's connect !"
          imageUrl: "Minimal Seth.png"
          imageWidth: 165
          imageHeight: 165
          buttons:
            - name: Papers
              url: papers/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            - name: Courses
              url: courses/
            # - name: Archive
            #   url: archive/
            - name: Notes
              url: https://seth-woo.github.io/

    socialIcons:
        - name: CV
          url: "Curriculum Vitae - Waihong Woo (Seth).pdf"
        - name: Email
          url: mailto:sethwoo555@gmail.com
        - name: ORCID
          url: https://orcid.org/0000-0002-0324-4815
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/seth-woo
        - name: linkedin
          url: https://www.linkedin.com/in/sethwoo/
        - name: x
          url: https://x.com/woogamanga
        - name: Mastodon
          url: https://mastodon.social/@seth_woo
        - name: Bluesky
          url: https://bsky.app/profile/sethwoo.bsky.social
        - name: instagram
          url: https://www.instagram.com/21.09_wh/
        - name: discord 
          url: https://discord.com/users/484731835990147088
        - name: whatsapp
          url: https://wa.me/60126942981
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: tiktok
        #   url: https://www.tiktok.com/@pmichaillat
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Seth Woo"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2